/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class SglangClient {
  static connect(endpoint: string, tokenizerPath: string): Promise<SglangClient>
  tokenizerEncode(text: string): Array<number>
  tokenizerDecode(tokenIds: Array<number>): string
  /**
   * Non-streaming chat completion
   * Returns the full JSON response string
   */
  chatCompletion(requestJson: string): Promise<string>
  /**
   * Streaming chat completion
   * Accepts a callback function that receives JSON chunks
   */
  chatCompletionStream(requestJson: string, callback: (err: null | Error, chunk: string) => void): void
}
